<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="DataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="EncryptMessanger.dll.Properties.Settings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Dialog" Member="Dialog">
    <Type Name="Dialog">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="creation_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Dialog_DialogMembers" Member="DialogMembers" ThisKey="id" OtherKey="dialog_id" Type="DialogMembers" />
      <Association Name="Dialog_Message" Member="Message" ThisKey="id" OtherKey="dialog_id" Type="Message" />
    </Type>
  </Table>
  <Table Name="dbo.DialogMembers" Member="DialogMembers">
    <Type Name="DialogMembers">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dialog_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="add_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="permission_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Dialog_DialogMembers" Member="Dialog" ThisKey="dialog_id" OtherKey="id" Type="Dialog" IsForeignKey="true" />
      <Association Name="Permission_DialogMembers" Member="Permission" ThisKey="permission_id" OtherKey="id" Type="Permission" IsForeignKey="true" />
      <Association Name="Users_DialogMembers" Member="Users" ThisKey="user_id" OtherKey="id" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Message" Member="Message">
    <Type Name="Message">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="text" Type="System.Data.Linq.Binary" DbType="Binary(1024)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="dialog_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="delivered" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Dialog_Message" Member="Dialog" ThisKey="dialog_id" OtherKey="id" Type="Dialog" IsForeignKey="true" />
      <Association Name="Users_Message" Member="Users" ThisKey="user_id" OtherKey="id" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Permission" Member="Permission">
    <Type Name="Permission">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="permission" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Permission_DialogMembers" Member="DialogMembers" ThisKey="id" OtherKey="permission_id" Type="DialogMembers" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ip" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
      <Column Name="hash" Type="System.Data.Linq.Binary" DbType="Binary(128)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Users_DialogMembers" Member="DialogMembers" ThisKey="id" OtherKey="user_id" Type="DialogMembers" />
      <Association Name="Users_Message" Member="Message" ThisKey="id" OtherKey="user_id" Type="Message" />
    </Type>
  </Table>
</Database>